//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokStore.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satıs
    {
        public int SATISID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<byte> ADET { get; set; }
        public decimal FIYAT { get; set; }
    
        public virtual tbl_musteriler tbl_musteriler { get; set; }
        public virtual tbl_urunler tbl_urunler { get; set; }
    }
}
